Modying jacoco report directory

diff --git a/.github/workflows/ci-pipeline.yml b/.github/workflows/ci-pipeline.yml
--- a/.github/workflows/ci-pipeline.yml
+++ b/.github/workflows/ci-pipeline.yml
@@ -30,20 +30,35 @@ jobs:
           restore-keys: |
             ${{ runner.os }}-maven-
 
-      - name: Build and test with Maven
-        run: mvn clean verify -Pexclude-e2e-tests
+      - name: Run Maven with Debug Info
+        run: mvn clean verify -X -Pexclude-e2e-tests  # Ejecutar con el perfil para excluir pruebas E2E
 
-      - name: Compress JaCoCo report
+      # Subir solo el reporte HTML de JaCoCo, si existe
+      - name: Compress JaCoCo HTML report if it exists
         run: |
           if [ -d "target/jacoco-reports" ]; then
-            zip -r jacoco-report.zip target/jacoco-reports/
+            zip -r jacoco-report.zip target/jacoco-reports/index.html
           else
             echo "JaCoCo report directory not found, skipping compression."
-            exit 1
           fi
 
-      - name: Upload compressed JaCoCo report
+      - name: Upload compressed JaCoCo report if it exists
+        if: success() && steps.compress.outputs.exists == 'true'
         uses: actions/upload-artifact@v3
         with:
           name: jacoco-html-report
           path: jacoco-report.zip
+
+      - name: Check test results
+        run: |
+          if grep -q "FAIL" target/surefire-reports/*.txt; then
+            echo "Tests failed!"
+            exit 1
+          else
+            echo "Tests passed!"
+          fi
+
+      - name: Wait for the test environment (Optional)
+        run: |
+          echo "Waiting for environment to settle..."
+          sleep 10
